### PR TITLE
Fix UserMetricsData Modal

### PR DESCRIPTION
**Pull request by j33l**
- Now displaying the modal with previously added user metrics data when user clicks on edit metrics data
- fixed some endpoints for data loading from firebase database and uploading to firebase database

### CODE REVIEW

**Comment by qtdinh** [comment]
I'll review the code, and try to merge this with issue #53 then link the issue once I'm done with that.

**Comment by qtdinh** [comment]
Merging done:
- Should fetch data _except_ for DOB. That was causing problems, and I don't know how the datepicker takes in values yet. The reason for using DOB in the first place is so that the profile screen calculates the age every time, which should take birthdays into account.
- Set DOB time to 0, birthdays should always happen when the day changes.
- Warning: Old accounts may not work due to the fact that documents used to have the age value in them. But now we're using dob again. @cfiguer055 Clean up your test accounts, or if you want, manually delete your documents one by one.

**Comment by cfiguer055** [comment]
**Manual Test on New Features:**
- Bad News
   - Age only goes up at the start of the year (January 1st).  I think the DOB date was set to 0 instead of DOB time.
   - For example, if birthday 1/1/1990 then 33 years old and if birthday 12/31/1989 then 34 years old.
   - If birthday is before or after the current date, then the age never changes.
   - Fetching DOB issue stated above causes DOB to be reset to current date.  This only happens after logout and then logging in. Can be avoided by cancelling modal or setting the date back to the real DOB.
   - Sometimes Height HelperText doesn't show units error. But Weight HelperText does work.
- Good News:
   -  Spacing in first and last name no longer causes firebase error.
   - Personal and Metrics modals both autofill fields with current data, with the exception of DOB. This makes it more unlikely for user to accidently change or delete current data. 
   -  Height and Weight fields in Metrics modal now requires units if the user decides to give metrics information.

*Due to changes in DOB and units drop-down, old accounts may have their previous metrics data altered, such as age: NaN.

**Regression Testing on New Features (Merged with Main):**
   - All testcases pass except for MyDevices (Refer to Issue #63 ) 
   - Details:
   - https://docs.google.com/document/d/1D4ptVtO3QrovgxngQkdTOpG5k1gA60JT/edit?usp=sharing&ouid=114415295023973896229&rtpof=true&sd=true

**Comment by qtdinh** [comment]
**Fixes:**
- DeviceDetails navigation was fixed in the settings branch, but I went ahead and did a hotfix. Better to get it solved now than in a later update.
- Problem was not DOB date being set to 0. The age calculation only took the year into account. I made an if block that compares months and days, and now it should work.
- Some HelperText fixes were made. Instead of working on height/weight and allocating time to that any longer, I feel like the slider will make our life so much easier. It's better to look into that. It'll improve our code maintainability and there's no need for input validation either.

**Comment by cfiguer055** [comment]
Manual Test on Fixes - PASS:
- DeviceDetails navigation works for both listed devices. No more Error (Issue 63 resolved).
- DOB calculates age by month/day/year instead of just the year.
- Both helperTexts for height and weight work consistently.

Re-Regression Test - PASS:
- Passes all test cases including my devices
- Details:
- https://docs.google.com/document/d/1tAn-H5fUFlCxRIfC1-twMv-3LnGwQBtQ/edit?usp=sharing&ouid=114415295023973896229&rtpof=true&sd=true

Ready for launch 🚀

**Review by akul43 — APPROVED** [review]

**Pull request merged**
