### PR TITLE
Added Modal for Adding and Updating User Personal Metrics Data

### PR DESCRIPTION
**Pull request by j33l**
Completed Issue #29

### CODE REVIEW

**Comment by akul43** [comment]
@cfiguer055
Please test new features and no newly introduced bug.

**Comment by cfiguer055** [comment]
Manual Test:
1. Login & Signup
   - Login works as expected and accounts for invalid logins.
   - Signup works as expected with one exception: the user personal metrics modal appears whether registration succeeds or fails.
2. Registration Error with Existing Email
   - When attempting to register with an email that already exists, the user personal metrics modal still shows up, even though the registration fails.
   - I noticed that signupwithemail is called with: {"dob": "1/1/2001", "gender": "female", "height": "111", "weight": "1111" in the console.
   - It seems that personal metrics are being updated during a failed registration attempt to an existing user, even though the registering user is never redirected to the dashboard.
3. Error Messages
   - Error messages make sense depending whether valid or invalid input in toasts, alerts, and HelperText.
4. User Personal Metric Input Validation
   - The user personal metric input doesn't have any formatting requirements such as date-of-birth: mm/dd/yyyy

**Comment by j33l** [comment]
> * When attempting to register with an email that already exists, the user personal metrics modal still shows up, even though the registration fails.
> * I noticed that signupwithemail is called with: {"dob": "1/1/2001", "gender": "female", "height": "111", "weight": "1111" in the console.
> * It seems that personal metrics are being updated during a failed registration attempt to an existing user, even though the registering user is never redirected to the dashboard.

Thank you for letting me know, I'll look into it.

**Comment by j33l** [comment]
@cfiguer055  Can you review new commits please. Thank you.

**Comment by fr1nc1sco** [comment]
**Manual Testing**

Login screen:
- Well designed.
- Text Input Boxes are very well designed and work properly.
- Will not allow login if there is a space character after email. Not a big deal but common when using autofill.
- "Forgot User..." link works.
- "Sign In" button works well
- ! If the app is reloaded (by pressing 'r' on the terminal that it's running on), the personal metrics window will appear again regardless of whether or not the information has been given/saved already.
- "Sign Up" link works.

Signup screen::
- Text Input Boxes are good
- Valid email checking works well.
- "Clear" button works .
- ! Able to create an account without checking the 'User Agreement' checkbox.

User Personal Metric screen:
- Gender scroll down menu works well. Possibly more options?
- DoB input is fantastic.
- ! Height and Weight inputs need work. Worth discussing.
- Skip button works.
- '! Save' button does not work. Always logs "FirebaseError: Function setDoc() called with invalid data...". "Save" text should be easier to read; the current color is hard to make out against the blue background.

**Comment by akul43** [comment]
User agreement check will be implemented with Issue#44

**Comment by qtdinh** [comment]
@cfiguer055 Both issues done. Tested the modal per Francisco's bullet points; height and weight will be revised later as a quick additional fix. Check jeel-firebase-auth and start testing. Thanks.

**Comment by cfiguer055** [comment]
Manual Test:

1. Login & Signup - PASS
   - Login works as expected and accounts for invalid logins.
   - Signup works as expected and accounts for invalid logins.
2. Registration one time modal popup - PASS
   - Metric modal does not appear anymore after registering with an existing email (invalid credentials).
   - Metric modal only appears after a successful one-time sign-up as expected.
   - Save button no longer displays Firebase error on console and proceeds to dashboard.
3. Edit Profile - PASS
   - Profile UI is great - separating sensitive personal information and optional metric info.
   - Edit Personal: Ensures these mandatory textFields are filled out
   - Edit Metrics: Optional no validation needed 
   - Pressing save successfully updates information onto database.
   - Updated information remains the same after logging out and logging back in.

New features metrics modal and edit profile are functional and error free. 
Ready for launch. 🚀

**Review by akul43 — APPROVED** [review]

**Pull request merged**
